### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by gusttavosouza** [Prototype-X/Zabbix-Network-Weathermap#20]
Good afternoon, I'm trying to do the zabbix integration with the weathermap but it arrived in a part that I'm getting the following Exception.

>  ` raise ZbxException ("hostname: {} not found" .format (hostname)`    

 Is hostname the host name in zabbix?

**Comment by gusttavosouza** [comment]
because I already put the name of my host in zabbix and even then the exception persists.

**Comment by Prototype-X** [comment]
Hi.
What version of Zabbix?
Is the host name written in English?
If you are using a Visible Name, try deleting it.

**Comment by gusttavosouza** [comment]
Hi.
I'm using version 3.4 of zabbix. The host is using what comes standard from zabbix the "Zabbix server" and it does not have a visible name.

**Comment by Prototype-X** [comment]
Show me links from config file.

**Comment by gusttavosouza** [comment]
Good Morning!
I have two hosts configured in Zabbix, which are the "Zabbix server" (node-Router) and the "test" (node-Router2).

```
node-Router:
  name: teste        
  label: R1            
  icon: Router64.png 
  x: 625
  y: 225
node-Router2:
  name: Zabbix server
  label: R2
  icon: Router64.png
  x: 625
  y: 225

link-1:
      node1: node-Router
      node2: node-Router2
      name1: R1
      name2: SW1
      width: 15
      hostname: Zabbix server
      #itemin/itemout = item key
      itemin: ifHCInOctets[ge-0/0/0]
      itemout: ifHCOutOctets[ge-0/0/0]
```

This is the problem.

![image](https://user-images.githubusercontent.com/22873208/35219590-76d9e95a-ff5a-11e7-8e32-59df797b92d3.png)
