### ISSUE TITLE
Separate  color indication for 1GB and 100MB links 

### ISSUE THREAD

**Issue by vyankatesh22** [Prototype-X/Zabbix-Network-Weathermap#42]
Hi,

We have multiple links some links are 1gbps and some links are 100mbps. I have specified link:                   # default settings link
bandwidth: 1000        # in Mbits/s
Now all links above 100mbps and 1gbps are showing in same color.
How could i separate color indication for links above 100mbps and 1gbps traffic speed? 

/Venky

**Comment by Prototype-X** [comment]
Hi,

The colors for all links are the same, but you can specify the bandwidth for each link.

```yaml
link:                   # default settings link
  bandwidth: 1000        # in Mbits/s
  width: 10             # width arrow in pixels
link-2:
  node1: node-Router2
  node2: node-Switch2
  name1: ''
  name2: ''
  bandwidth: 100        # Override default settings in link
  hostname: Router2
  itemin: ifHCInOctets[ge-0/0/1]
  itemout: ifHCOutOctets[ge-0/0/1]
```
