### ISSUE TITLE
Question about Links

### ISSUE THREAD

**Issue by daniloulbrecht** [Prototype-X/Zabbix-Network-Weathermap#43]
First of all, congratulations for this project.
Is there a way to overcome this boring behavior?
https://support.zabbix.com/browse/ZBXNEXT-442

For example, in my map I have only two devices connected each other with two links, but I can only see one link, because one stay behind another.

link-1:
  node1: node-2
  node2: node-3
  name1: Switch_L2
  name2: Switch_L3
  hostname: Switch_L3
  itemin: net.if.in[ifHCInOctets.1]
  itemout: net.if.out[ifHCOutOctets.1]
link-2:
  node1: node-2
  node2: node-3
  name1: Switch_L2
  name2: Switch_L3
  hostname: Switch_L3
  itemin: net.if.in[ifHCInOctets.2]
  itemout: net.if.out[ifHCOutOctets.2]
link-4:
  node1: node-6
  node2: node-3
  name1: Cloud_(128)
  name2: Switch_L3
  hostname: Switch_L3
  itemin: net.if.in[ifHCInOctets.3]
  itemout: net.if.out[ifHCOutOctets.3]

Thank you!
![capture](https://user-images.githubusercontent.com/33044136/46881942-65afd700-ce23-11e8-934f-16551d9184ea.PNG)

**Comment by Prototype-X** [comment]
Hi,
Thanks.
There is a solution to this problem:
https://github.com/Prototype-X/Zabbix-Network-Weathermap/issues/23

**Comment by daniloulbrecht** [comment]
The solution https://github.com/Prototype-X/Zabbix-Network-Weathermap/issues/23 does not work as expected. The only thing was made was a copy of one link (node x to node y) to another new link. But my problem is other, the links stays one under another. Is there any workaround?

Thank you.

**Comment by Prototype-X** [comment]
Yes. Open mapname.yaml file find link with option copy: true and change node x, y(for node-nridx7c0 and node-uwf443jw). Modify x, y until these links are fully visible.
```YAML
node-nridx7c0:
  name: net1
  x: 10
  y: 20
node-uwf443jw:
  name: net1
  x: 870
  y: 500
link-lyonlz7x:
  node1: node-nridx7c0
  node2: node-uwf443jw
  name1: net1
  name2: net2
  copy: true
  hostname: R10
  itemin: ifHCOutOctets[1/6]
  itemout: ifHCInOctets[1/6]
```
